export const scriptures = [
  {
    id: "new-creation",
    category: "New Creation",
    icon: "✨",
    title: "I Am a New Creation",
    ref: "2 Corinthians 5:17",
    text: "If anyone is in Christ, the new creation has come; the old has gone, the new is here.",
  },
  {
    id: "workmanship",
    category: "Purpose",
    icon: "🎨",
    title: "I Am God's Workmanship",
    ref: "Ephesians 2:10",
    text: "We are God's workmanship, created in Christ Jesus to do good works.",
  },
  {
    id: "no-condemnation",
    category: "Freedom",
    icon: "🕊️",
    title: "I Am Free from Condemnation",
    ref: "Romans 8:1",
    text: "There is now no condemnation for those who are in Christ Jesus.",
  },
  {
    id: "christ-lives",
    category: "Union With Christ",
    icon: "🔥",
    title: "Christ Lives in Me",
    ref: "Galatians 2:20",
    text: "I have been crucified with Christ and Christ lives in me; I live by faith in the Son of God.",
  },
  {
    id: "hidden",
    category: "Security",
    icon: "🛡️",
    title: "My Life Is Hidden With Christ",
    ref: "Colossians 3:3",
    text: "You died, and your life is now hidden with Christ in God.",
  },
  {
    id: "blessed",
    category: "Blessed",
    icon: "🌿",
    title: "I Am Spiritually Blessed",
    ref: "Ephesians 1:3",
    text: "God has blessed us in Christ with every spiritual blessing in the heavenly realms.",
  },
  {
    id: "heaven",
    category: "Citizenship",
    icon: "🏠",
    title: "I Am a Citizen of Heaven",
    ref: "Philippians 3:20",
    text: "Our citizenship is in heaven, and we eagerly await a Savior from there—the Lord Jesus Christ.",
  },
  {
    id: "temple",
    category: "Holy Spirit",
    icon: "🕯️",
    title: "I Am God's Temple",
    ref: "1 Corinthians 6:19–20",
    text: "Your body is a temple of the Holy Spirit, whom you have from God. You were bought with a price.",
  },
  {
    id: "friend",
    category: "Friendship",
    icon: "🤝",
    title: "I Am Christ's Friend",
    ref: "John 15:15",
    text: "Jesus says, 'I have called you friends,' making known to His followers what He received from the Father.",
  },
  {
    id: "conqueror",
    category: "Victory",
    icon: "⚔️",
    title: "I Am More Than a Conqueror",
    ref: "Romans 8:37",
    text: "In all these things we are more than conquerors through Him who loved us.",
  },
  {
    id: "righteous",
    category: "Righteousness",
    icon: "✨",
    title: "I Am Made Righteous in Christ",
    ref: "2 Corinthians 5:21",
    text: "In Christ, we become the righteousness of God.",
  },
  {
    id: "ambassador",
    category: "Purpose",
    icon: "📣",
    title: "I Am Christ's Ambassador",
    ref: "2 Corinthians 5:20",
    text: "We are therefore Christ's ambassadors, as though God were making His appeal through us.",
  },
  {
    id: "adopted",
    category: "Adoption",
    icon: "👨‍👩‍👧",
    title: "I Am Adopted by God",
    ref: "Ephesians 1:5",
    text: "God predestined us for adoption to sonship through Jesus Christ.",
  },
  {
    id: "sealed",
    category: "Holy Spirit",
    icon: "🔐",
    title: "I Am Sealed by the Holy Spirit",
    ref: "Ephesians 1:13",
    text: "Having believed, you were marked in Christ with a seal, the promised Holy Spirit.",
  },
  {
    id: "alive",
    category: "New Life",
    icon: "🌱",
    title: "I Am Alive With Christ",
    ref: "Ephesians 2:5",
    text: "God made us alive with Christ even when we were dead in transgressions.",
  },
  {
    id: "complete",
    category: "Identity",
    icon: "💎",
    title: "I Am Complete in Christ",
    ref: "Colossians 2:10",
    text: "In Christ you have been brought to fullness.",
  },
  {
    id: "light",
    category: "Light",
    icon: "💡",
    title: "I Am the Light of the World",
    ref: "Matthew 5:14",
    text: "Jesus tells His disciples, 'You are the light of the world.'",
  },
  {
    id: "salt",
    category: "Influence",
    icon: "🧂",
    title: "I Am Salt of the Earth",
    ref: "Matthew 5:13",
    text: "Jesus says, 'You are the salt of the earth.'",
  },
  {
    id: "chosen",
    category: "Chosen",
    icon: "👑",
    title: "I Am Chosen",
    ref: "1 Peter 2:9",
    text: "But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light.",
  },
  {
    id: "chosen",
    category: "Chosen",
    icon: "👑",
    title: "I am God's special possession",
    ref: "1 Peter 2:10",
    text: "Which in time past were not a people, but are now the people of God: which had not obtained mercy, but now have obtained mercy.",
  },
  {
    id: "chosen",
    category: "Chosen",
    icon: "👑",
    title: "I am chosen by God",
    ref: "Ephesians 1:4",
    text: "According as he hath chosen us in him before the foundation of the world, that we should be holy and without blame before him in love.",
  },
  {
    id: "chosen",
    category: "Chosen",
    icon: "👑",
    title: "I am God's elect",
    ref: "Colossians 3:12",
    text: "Put on therefore, as the elect of God, holy and beloved, bowels of mercies, kindness, humbleness of mind, meekness, longsuffering.",
  },
  {
    id: "chosen",
    category: "Chosen",
    icon: "👑",
    title: "I am chosen according to God's purpose",
    ref: "Romans 8:28",
    text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
  },
  {
    id: "chosen",
    category: "Chosen",
    icon: "👑",
    title: "I am accepted in Christ",
    ref: "Ephesians 1:6",
    text: "To the praise of the glory of his grace, wherein he hath made us accepted in the beloved.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I Am a Child of God",
    ref: "John 1:12",
    text: "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I am God's child",
    ref: "1 John 3:1",
    text: "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I am born of God",
    ref: "John 1:13",
    text: "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I am born again",
    ref: "1 Peter 1:3",
    text: "Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I am born of the Spirit",
    ref: "John 3:5-8",
    text: "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God. That which is born of the flesh is flesh; and that which is born of the Spirit is spirit. Marvel not that I said unto thee, Ye must be born again. The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I have received the Spirit of adoption",
    ref: "Romans 8:15",
    text: "For ye have not received the spirit of bondage again to fear; but ye have received the Spirit of adoption, whereby we cry, Abba, Father.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I am God's son/daughter through faith",
    ref: "Galatians 3:26",
    text: "For ye are all the children of God by faith in Christ Jesus.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I am no longer a slave but a child",
    ref: "Galatians 4:7",
    text: "Wherefore thou art no more a servant, but a son; and if a son, then an heir of God through Christ.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I am an heir with Christ",
    ref: "Romans 8:17",
    text: "And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I have access to the Father",
    ref: "Romans 8:17",
    text: "For through him we both have access by one Spirit unto the Father.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "God is my Father",
    ref: "Matthew 6:9",
    text: "After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name.",
  },
  {
    id: "child",
    category: "Child of God",
    icon: "🤍",
    title: "I belong to God's family",
    ref: "Ephesain 2:19",
    text: "Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God.",
  },
];
